[phases.setup]
nixPkgs = ["python39", "mysql80"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p static/uploads"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"